#======================================================================#
#  Digital Notepad Computer Company. 2024-2025. All rights reserved.   #
#    Makefile for StellarGIM Kernel                                    #
#  Date Created: Jan 4,2025                                            #
#======================================================================#

#******************* Makefile for KERNEL\... *******************#

msg = ../MESSAGES
inc = ../inc
dos = ../system

##################### Dependencies Begin here #####################

all: kernel.exe

# handle first the assembly

# then the ".C"

main.obj : main.c \
           errors.h

errors.obj : errors.c \
             errors.h

kernel.exe : main.obj errors.obj
         link @kernel.lnk