/**************************************************************************
 *                                                                        *
 *      VERSION.H          -- Version information for internal builds     *
 *                                                                        *
 *  This file is only modified by the official builder to update the      *
 *  VERSION, VER_PRODUCTVERSION and VER_PRODUCTVERSION_STR values         *
 *                                                                        *
 **************************************************************************/
 
/*--------------------------------------------------------------*/
/*                                                              */
/* the following entry should be phased out in favor of         */
/* VER_PRODUCTVERSION_STR, but is used in the shell today.      */
/*                                                              */
/*==============================================================*/
/*                                                              */
/* the following values should be modified by the official      */
/* builder for each build                                       */
/*                                                              */
/*--------------------------------------------------------------*/

#define VERSION					"0.0"
#define VER_PRODUCTVERSION_STR	"0.0\0"
#define VER_PRODUCTVERSION		0,00
#define VER_PRODUCTBUILD		7
