#======================================================================#
#  Digital Notepad Computer Company. 2024-2025. All rights reserved.   #
#    Makefile for StellarGIM GDI (Graphical Device Interface)          #
#  Date Created: Jan 4,2025                                            #
#======================================================================#

#******************* Makefile for GDI\... *******************#

msg = ../MESSAGES
inc = ../inc
dos = ../system

##################### Dependencies Begin here #####################

all: gdi.exe

# handle first the ".ASM"

hello.obj : hello.asm

gdi.exe : hello.obj
         link @gdi.lnk